# Generated by Django 4.0 on 2021-12-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=25)),
                ('fullname', models.CharField(default='', max_length=25)),
                ('position', models.CharField(default='', max_length=25)),
                ('company', models.CharField(default='', max_length=25)),
                ('email', models.CharField(default='', max_length=25)),
                ('saddr1', models.CharField(default='', max_length=25)),
                ('saddr2', models.CharField(default='', max_length=25)),
                ('country', models.CharField(default='', max_length=25)),
                ('city', models.CharField(default='', max_length=25)),
                ('state', models.CharField(default='', max_length=25)),
                ('zip', models.IntegerField(default='', max_length=6)),
                ('phone', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
